// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmhenslbccgvmbkvvqmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtaGVuc2xiY2Nndm1ia3Z2cW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjMwMjEsImV4cCI6MjA2Njc5OTAyMX0.ypyYV1z7UU_qfT6yThOU0nLMRkk8hFaF_yOBjkW0zuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});